### PR TITLE
fix date encodings

### PR DESCRIPTION
**Pull request by rbren**

### CODE REVIEW

**Comment by bobby-brennan** [comment]
This is a copy of #15 with a cleaned up diff.

I do think it would be a bit safer to use the UTC string with milliseconds removed, rather than re-encoding the offset. Happy to do that if you agree.

**Comment by bobby-brennan** [comment]
Sorry, I think I meant ISO string.

Right now the code lops off milliseconds and timezone data, then adds back the timezone data using `date.offset`...I think we could just slice out the milliseconds, and the ISO timezone string would match what the code currently calculates using `date.offset`.

**Comment by creationix** [comment]
As long as the tests pass and information isn't thrown away, I'm not particular on how it's implemented.

**Comment by creationix** [comment]
My understanding is JS Date objects can't store timezones.  Make sure to test on several JS engines in case on non-standard behavior that makes it pass on just some.

**Pull request merged**
